import type { Metadata } from "next";
import "./globals.css";
import { Header } from "../../components/header";
import { Inter } from "next/font/google";
import { WhatsAppButton } from "../../components/whatsapp-button";
import { BannerAge } from "../../components/banner-age";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "PrivTime",
  description: "Generated by PrivTime",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${inter.variable} antialiased relative`}>
        {children}
        <BannerAge></BannerAge>
        <WhatsAppButton></WhatsAppButton>
      </body>
    </html>
  );
}
